dist: bionic
language: node_js
node_js:
- '8'
run:
- npm run build
cache:
  directories:
  - "~/.npm"
deploy:
  provider: heroku
  api_key:
      secure: PDbMowCtuboIECkdzdt9gNLxRJPuwgVT/d2/EZZ119qvgIs6CgNvOs2BJX9DZAlj1FoiyZs/nlSaYM+eUXk576GZG0g4f3qAsX7op1cJuSCiZmTQcCg2SJxrUmRVdBAZUGnAtUzhtWn1fhGluiNdtKH/2yHrpQu6nAffSemuPdGcnDsdOJycj/JG+sE4YHz4Fn3Epl9ToKbYJ9xERg0lae2uitc2dgzP949nEIn9o3z2vkakZhCnJBSZBdinN5pv2JZ8I+OO1pa10sUUSs+sL/LbljC6xtrtoyZYr/Ap8kD1WZRQdF4WWhGka5zU9ziGrZi75d7euKap55Bk/kWE6S/jB/W8LXkUV9txreyC/dwTKWF/daB65OAxaKtrehhkiQyXTX8JPzKNtbz9G2m2Pj15/QH2bHCBFo8ofhAKdiBYwYov+TzxUtAwzKgYhzbVyqf0Or9gCajLvK72AJEUPB9TgpATwc1jaXc3ywjGTtI/Tw8jOVKwotJ+Hmaq6JkPcbUh4x8nji1d06RJwVxfahZcQG8WQGwNOxT+A92Ss698g1dFiZFzbeXQ/RPudkEukGlnMPU/d7oPxNdkCegGIkBwrgkr5EE0uJPdlajTzHVjXqvCMhcq+lXVIYl8mZ1hWpgkjYyJx6BYsd6qB2JoM3t3qy/9LaF52jCCINuiQqw=
  app: covider-ui
  on: master